### Exercise 1
Suppose the people who own page 3 in the web of Figure 1 are infuriated by the
fact that its importance score, computed using formula (2.1), is lower than the score of page 1. In
an attempt to boost page 3’s score, they create a page 5 that links to page 3; page 3 also links to page
5. Does this boost page 3’s score above that of page 1?

![image](./img/image.png)

In [4]:
import numpy as np

A = np.array([[0, 0, 1, 1/2],
         [1/3, 0, 0, 0],
         [1/3, 1/2, 0, 1/2],
         [1/3, 1/2, 0, 0]])

A_mod = np.array([[0, 0, 1/2, 1/2, 0],
         [1/3, 0, 0, 0, 0],
         [1/3, 1/2, 0, 1/2, 1],
         [1/3, 1/2, 0, 0, 0],
         [0, 0, 1/2, 0, 0]])

#print(A)
print(np.array2string(A, formatter={'float_kind':lambda x: "%.3f" % x}))
#print(A_mod)
print(np.array2string(A_mod, formatter={'float_kind':lambda x: "%.3f" % x}))

[[0.000 0.000 1.000 0.500]
 [0.333 0.000 0.000 0.000]
 [0.333 0.500 0.000 0.500]
 [0.333 0.500 0.000 0.000]]
[[0.000 0.000 0.500 0.500 0.000]
 [0.333 0.000 0.000 0.000 0.000]
 [0.333 0.500 0.000 0.500 1.000]
 [0.333 0.500 0.000 0.000 0.000]
 [0.000 0.000 0.500 0.000 0.000]]


In [5]:
#Stockastic check
def isSto(A): 
    col_sums = A_mod.sum(axis=0)
    return (col_sums == 1).all()

if isSto(A):
    print("A is stochastic")
if isSto(A_mod):
    print("A_mod is stochastic")


A is stochastic
A_mod is stochastic


In [6]:

def print_eig(label, eigvals, eigvecs):
    print(f"\n=== Eigen Decomposition for {label} ===")
    for i, (val, vec) in enumerate(zip(eigvals, eigvecs.T), 1):
        print(f"Eigenvalue {i}: {val:.6f}")
        print(f"Eigenvector {i}: {vec}")
        print("-" * 40)


eigvals_A, eigvecs_A = np.linalg.eig(A)
eigvals_Am, eigvecs_Am = np.linalg.eig(A_mod)

#print_eig("A", eigvals_A, eigvecs_A)
#print_eig("A_mod", eigvals_Am, eigvecs_Am)

# Function
def standardizer(x, round=3):
    sum = x.sum()
    x = x/sum
    return np.round(x, round)


index = np.where(np.isclose(eigvals_A, 1.0, atol=1e-8)) # we cannot use np.where because of rounding errors
A_std = np.real(standardizer(eigvecs_A.T[index]))[0]
print(A_std)
index = np.where(np.isclose(eigvals_Am, 1.0, atol=1e-8))
Am_std = np.real(standardizer(eigvecs_Am.T[index]))[0]
print(Am_std)

[0.387 0.129 0.29  0.194]
[0.245 0.082 0.367 0.122 0.184]


In [7]:

def rank(A):
    ranking = dict()
    n = 1
    for i in A:
        ranking[n] = float(i)
        n+=1
    return ranking

print(rank(A_std))
print(rank(Am_std))


{1: 0.387, 2: 0.129, 3: 0.29, 4: 0.194}
{1: 0.245, 2: 0.082, 3: 0.367, 4: 0.122, 5: 0.184}


## Exercise 4
In the web of Figure 2.1, remove the link from page 3 to page 1. In the resulting
web page 3 is now a dangling node. Set up the corresponding substochastic matrix and find its largest
positive (Perron) eigenvalue. Find a non-negative Perron eigenvector for this eigenvalue, and scale
the vector so that components sum to one. Does the resulting ranking seem reasonable?

In [8]:
B = np.array([[0, 0, 0, 1/2],
         [1/3, 0, 0, 0],
         [1/3, 0, 0, 1/2],
         [1/3, 1, 0, 0]])

In [9]:
def get_perron(matrix):
    A = np.array(matrix, dtype = float)
    eigvals, eigvecs = np.linalg.eig(matrix)
    idx = np.argmax(np.abs(eigvals))

    perron_eigenvalue = eigvals[idx].real
    perron_eigenvector = eigvecs[:, idx].real

        # Make the eigenvector non-negative (flip sign if needed)
    if perron_eigenvector[0] < 0:
        perron_eigenvector = -perron_eigenvector
    
    # Normalize to sum to 1 (or L2 norm = 1, depending on preference)
    perron_eigenvector = standardizer(perron_eigenvector)
    
    return perron_eigenvalue, perron_eigenvector

print(get_perron(B))

(np.float64(0.6503404456767778), array([0.231, 0.118, 0.35 , 0.301]))


This substochastic matrix representing the web described previously, lead to a rank as follow:
- Page 3
- Page 4
- Page 1
- Page 2

This does make sense because a web user after a finite number of 'random click' would reach the page 3. After that it would be stuck because page 3 does not link to any other page.

## Exercise 13 
Construct a web consisting of two or more subwebs and determine the ranking given by formula (3.1).

![image](./img/ex_13.png)

In [11]:
def PowerMethod(A, N, m=0.15, dangling_nodes=None, relTol=1e-10, maxiter=500):
    # Initialize s (vector of lenght N with all values = 1/N)
    s = np.full((N, 1), 1.0 / N)

    # Initialize and normalize xk (the starting vector)
    xk = s.copy()
    xk = xk / np.linalg.norm(xk, ord=1) 
    k = 0 
    lambda_k = 0

    while k < maxiter:
        
        dangling_sum = np.sum(xk[dangling_nodes])

        dangling_part = dangling_sum * s
        # Compute the new vector x_tilde_k+1, this is a vector NOT NORMALIZED
        # This computation exploits the sparsity of the matrix A by computing the @ product of A @ xk

        xk_new_tilde = (1 - m) * (A @ xk + dangling_part) + (m * s) 
                        
        # Rayleigh quotient - Compute the eigenvalue
        lambda_k_new = float((xk.T @ xk_new_tilde) / (xk.T @ xk))
        # Normalize the xk_tilde
        norm_val = np.linalg.norm(xk_new_tilde, ord=1)
        xk_new = xk_new_tilde / norm_val
        
        #Check the convergence
        diff = np.abs(lambda_k_new - lambda_k)
        if diff < relTol * np.abs(lambda_k_new):

            print(f"Convergenza raggiunta all'iterazione {k+1}")
            xk = xk_new
            break
        
        xk = xk_new
        k += 1
        lambda_k = lambda_k_new

    print(lambda_k)
    return xk

In [ ]:
A = np.array([[0, 0, 1, 1/2, 0, 0, 0],
              [1/3, 0, 0, 0, 0, 0, 0],
              [1/3, 1/2, 0, 1/2, 0, 0, 0],
              [1/3, 1/2, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 1/2],
              [0, 0, 0, 0, 0, 0, 1/2],
              [0, 0, 0, 0, 1, 0, 0]])

# --- Esecuzione PageRank ---
N=7
m = 0.15
ranks = PowerMethod(A, N, m=m)
flat_ranks = ranks.flatten()
sorted_indices = np.argsort(flat_ranks)[::-1]

print("\n--- Rank ---")
print(f"{'Rank':<5} {'Score':<12} {'ID':<6} {'URL'}")
print("-" * 60)

for i in range(N):
    idx = sorted_indices[i]
    score = flat_ranks[idx]        
    print(f"{i+1:<5} {score:.8f}")

Convergenza raggiunta all'iterazione 19
1.8499999999702375

--- Rank ---
Rank  Score        ID     URL
------------------------------------------------------------
1     0.17956575
2     0.16382730
3     0.15836299
4     0.15249208
5     0.12877870
6     0.11225204
7     0.10472114


/var/folders/j9/m1q0h7955ls67lg17_lw___80000gn/T/ipykernel_66863/1719758957.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  lambda_k_new = float((xk.T @ xk_new_tilde) / (xk.T @ xk))
