### Exercise 1
Suppose the people who own page 3 in the web of Figure 1 are infuriated by the
fact that its importance score, computed using formula (2.1), is lower than the score of page 1. In
an attempt to boost page 3’s score, they create a page 5 that links to page 3; page 3 also links to page
5. Does this boost page 3’s score above that of page 1?

![image](./img/image.png)

In [3]:
import numpy as np

A = np.array([[0, 0, 1, 1/2],
         [1/3, 0, 0, 0],
         [1/3, 1/2, 0, 1/2],
         [1/3, 1/2, 0, 0]])

A_mod = np.array([[0, 0, 1/2, 1/2, 0],
         [1/3, 0, 0, 0, 0],
         [1/3, 1/2, 0, 1/2, 1],
         [1/3, 1/2, 0, 0, 0],
         [0, 0, 1/2, 0, 0]])

#print(A)
print(np.array2string(A, formatter={'float_kind':lambda x: "%.3f" % x}))
#print(A_mod)
print(np.array2string(A_mod, formatter={'float_kind':lambda x: "%.3f" % x}))

[[0.000 0.000 1.000 0.500]
 [0.333 0.000 0.000 0.000]
 [0.333 0.500 0.000 0.500]
 [0.333 0.500 0.000 0.000]]
[[0.000 0.000 0.500 0.500 0.000]
 [0.333 0.000 0.000 0.000 0.000]
 [0.333 0.500 0.000 0.500 1.000]
 [0.333 0.500 0.000 0.000 0.000]
 [0.000 0.000 0.500 0.000 0.000]]


In [4]:
#Stockastic check
def isSto(A): 
    col_sums = A_mod.sum(axis=0)
    return (col_sums == 1).all()

if isSto(A):
    print("A is stochastic")
if isSto(A_mod):
    print("A_mod is stochastic")


A is stochastic
A_mod is stochastic


In [5]:

def print_eig(label, eigvals, eigvecs):
    print(f"\n=== Eigen Decomposition for {label} ===")
    for i, (val, vec) in enumerate(zip(eigvals, eigvecs.T), 1):
        print(f"Eigenvalue {i}: {val:.6f}")
        print(f"Eigenvector {i}: {vec}")
        print("-" * 40)


eigvals_A, eigvecs_A = np.linalg.eig(A)
eigvals_Am, eigvecs_Am = np.linalg.eig(A_mod)

#print_eig("A", eigvals_A, eigvecs_A)
#print_eig("A_mod", eigvals_Am, eigvecs_Am)

# Function
def standardizer(x, round=3):
    sum = x.sum()
    x = x/sum
    return np.round(x, round)


index = np.where(np.isclose(eigvals_A, 1.0, atol=1e-8)) # we cannot use np.where because of rounding errors
A_std = np.real(standardizer(eigvecs_A.T[index]))[0]
print(A_std)
index = np.where(np.isclose(eigvals_Am, 1.0, atol=1e-8))
Am_std = np.real(standardizer(eigvecs_Am.T[index]))[0]
print(Am_std)

[0.387 0.129 0.29  0.194]
[0.245 0.082 0.367 0.122 0.184]


In [6]:

def rank(A):
    ranking = dict()
    n = 1
    for i in A:
        ranking[n] = float(i)
        n+=1
    return ranking

print(rank(A_std))
print(rank(Am_std))


{1: 0.387, 2: 0.129, 3: 0.29, 4: 0.194}
{1: 0.245, 2: 0.082, 3: 0.367, 4: 0.122, 5: 0.184}


## Exercise 4
In the web of Figure 2.1, remove the link from page 3 to page 1. In the resulting
web page 3 is now a dangling node. Set up the corresponding substochastic matrix and find its largest
positive (Perron) eigenvalue. Find a non-negative Perron eigenvector for this eigenvalue, and scale
the vector so that components sum to one. Does the resulting ranking seem reasonable?

In [7]:
B = np.array([[0, 0, 0, 1/2],
         [1/3, 0, 0, 0],
         [1/3, 0, 0, 1/2],
         [1/3, 1, 0, 0]])

In [8]:
def get_perron(matrix):
    A = np.array(matrix, dtype = float)
    eigvals, eigvecs = np.linalg.eig(matrix)
    idx = np.argmax(np.abs(eigvals))

    perron_eigenvalue = eigvals[idx].real
    perron_eigenvector = eigvecs[:, idx].real

        # Make the eigenvector non-negative (flip sign if needed)
    if perron_eigenvector[0] < 0:
        perron_eigenvector = -perron_eigenvector
    
    # Normalize to sum to 1 (or L2 norm = 1, depending on preference)
    perron_eigenvector = standardizer(perron_eigenvector)
    
    return perron_eigenvalue, perron_eigenvector

print(get_perron(B))

(np.float64(0.6503404456767778), array([0.231, 0.118, 0.35 , 0.301]))


This substochastic matrix representing the web described previously, lead to a rank as follow:
- Page 3
- Page 4
- Page 1
- Page 2

This does make sense because a web user after a finite number of 'random click' would reach the page 3. After that it would be stuck because page 3 does not link to any other page.

## Exercise 13 
Construct a web consisting of two or more subwebs and determine the ranking given by formula (3.1).

![image](./img/ex_13.png)

In [14]:
from functions.graph import *
from functions.functions import *

# Create the nodes
node1 = Node(number=1)
node2 = Node(number=2)
node3 = Node(number=3)
node4 = Node(number=4)
node5 = Node(number=5)
node6 = Node(number=6)
node7 = Node(number=7)

# linking edges
node1.addOut([2,3,4]) 
node1.addIn([3,4]) 
node2.addIn([1]) 
node2.addOut([3,4]) 
node3.addIn([1,2,4]) 
node3.addOut([1]) 
node4.addIn([2,1]) 
node4.addOut([1,3]) 
node5.addOut([7]) 
node5.addIn([6,7]) 
node6.addOut([5]) 
node6.addIn([7]) 
node7.addIn([5]) 
node7.addOut([5,6]) 

graph = Graph([node1, node2, node3, node4, node5, node6, node7])
graph.print()
graph.plot()
testRank(graph)

Node(number=1, out=[2. 3. 4.], in=[3. 4.])
Node(number=2, out=[3. 4.], in=[1.])
Node(number=3, out=[1.], in=[1. 2. 4.])
Node(number=4, out=[1. 3.], in=[2. 1.])
Node(number=5, out=[7.], in=[6. 7.])
Node(number=6, out=[5.], in=[7.])
Node(number=7, out=[5. 6.], in=[5.])

Generazione grafico stabile con layout circolare...


Nodi totali: 7
Nodi dangling: 0
Convergenza raggiunta all'iterazione 34 (Diff: 8.69e-09)

--- Rank ---
Rank  Score        ID     URL
------------------------------------------------------------
1     0.21037182   1     
2     0.17031414   5     
3     0.16619559   7     
4     0.16454950   3     
5     0.11547333   4     
6     0.09206170   6     
7     0.08103392   2     


In [ ]:
A = np.array([[0, 0, 1, 1/2, 0, 0, 0],
              [1/3, 0, 0, 0, 0, 0, 0],
              [1/3, 1/2, 0, 1/2, 0, 0, 0],
              [1/3, 1/2, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 1/2],
              [0, 0, 0, 0, 0, 0, 1/2],
              [0, 0, 0, 0, 1, 0, 0]])

# --- Esecuzione PageRank ---
N=7
m = 0.15
ranks = PowerMethod(A, N, m=m)
flat_ranks = ranks.flatten()
sorted_indices = np.argsort(flat_ranks)[::-1]

print("\n--- Rank ---")
print(f"{'Rank':<5} {'Score':<12} {'ID':<6} {'URL'}")
print("-" * 60)

for i in range(N):
    idx = sorted_indices[i]
    node_real_id = mapping[idx]
    score = flat_ranks[idx]        
    print(f"{i+1:<5} {score:.8f}   {node_real_id:<6}")

Convergenza raggiunta all'iterazione 39
1.000000000014894

--- Rank ---
Rank  Score        ID     URL
------------------------------------------------------------
1     0.21037182
2     0.17031414
3     0.16619559
4     0.16454950
5     0.11547333
6     0.09206170
7     0.08103392


/var/folders/gw/h_3h_b5d74v_ds3nx7nhw4hh0000gn/T/ipykernel_54800/394013166.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  lambda_k_new = float((xk.T @ xk_new_tilde) / (xk.T @ xk))
